name: Build on Push

on:
  push:
    branches:
      - no-std  # Adjust this to your main branch name

jobs:
  build-win32:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'  # Specify the desired Python version

      - name: Set up AMBuilder
        run: |
          git clone https://github.com/alliedmodders/ambuild
          cd ambuild
          python setup.py install

      - name: Set up MSVC++ environment
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x86

      - name: Build project
        run: |
          mkdir build
          cd build
          python ../configure.py --enable-optimize
          ambuild

      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: build-win32
          path: build/oo_amxx/oo_amxx.dll

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AMBuilder
        run: |
          git clone https://github.com/alliedmodders/ambuild
          cd ambuild
          python setup.py install

      - name: Build project
        run: |
          mkdir build
          cd build
          python ../configure.py --enable-optimize
          ambuild

      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: build-linux
          path: build/oo_amxx/oo_amxx_i386.so
